apps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    ProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("product/<pk>/", ProductView.as_view(), name="product"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payment/<payment_option>/", PaymentView.as_view(), name="payment"),
    path("add-to-cart/<pk>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<pk>/", remove_from_cart, name="remove-from-cart"),
    path(
        "reduce-quantity-item/<pk>/", reduce_quantity_item, name="reduce-quantity-item"
    ),
]

core/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField

CATEGORY = (("S", "Shirt"), ("SP", "Sport Wear"), ("OW", "Out Wear"))

LABEL = (("N", "New"), ("BS", "Best Seller"))


class Item(models.Model):
    item_name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY, max_length=2)
    label = models.CharField(choices=LABEL, max_length=2)
    description = models.TextField()

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"pk": self.pk})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"pk": self.pk})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"pk": self.pk})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    checkout_address = models.ForeignKey(
        "CheckoutAddress", on_delete=models.SET_NULL, blank=True, null=True
    )
    payment = models.ForeignKey(
        "Payment", on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class CheckoutAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT = (("S", "Stripe"), ("P", "PayPal"))


class CheckoutForm(forms.Form):
    street_address = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "1234 Main St"}
        )
    )

    apartment_address = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Apartment or suite"}
        ),
    )

    country = CountryField(blank_label="(select country)").formfield(
        widget=CountrySelectWidget(attrs={"class": "custom-select d-block w-100"})
    )

    zip = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    same_billing_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT)

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from .forms import CheckoutForm
from .models import Item, Order, OrderItem, CheckoutAddress, Payment

import stripe

stripe.api_key = settings.STRIPE_KEY

# Create your views here.
class HomeView(ListView):
    model = Item
    template_name = "core/home.html"


class ProductView(DetailView):
    model = Item
    template_name = "core/product.html"


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):

        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {"object": order}
            return render(self.request, "core/order_summary.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect("/")


class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {"form": form, "order": order}
        return render(self.request, "core/checkout.html", context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)

        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get("street_address")
                apartment_address = form.cleaned_data.get("apartment_address")
                country = form.cleaned_data.get("country")
                zip = form.cleaned_data.get("zip")
                # TODO: add functionaly for these fields
                # same_billing_address = form.cleaned_data.get('same_billing_address')
                # save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get("payment_option")

                checkout_address = CheckoutAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip=zip,
                )
                checkout_address.save()
                order.checkout_address = checkout_address
                order.save()

                if payment_option == "S":
                    return redirect("core:payment", payment_option="stripe")
                elif payment_option == "P":
                    return redirect("core:payment", payment_option="paypal")
                else:
                    messages.warning(self.request, "Invalid Payment option")
                    return redirect("core:checkout")

        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect("core:order-summary")


class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {"order": order}
        return render(self.request, "core/payment.html", context)

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get("stripeToken")
        amount = int(order.get_total_price() * 100)  # cents

        try:
            charge = stripe.Charge.create(amount=amount, currency="usd", source=token)

            # create payment
            payment = Payment()
            payment.stripe_id = charge["id"]
            payment.user = self.request.user
            payment.amount = order.get_total_price()
            payment.save()

            # assign payment to order
            order.ordered = True
            order.payment = payment
            order.save()

            messages.success(self.request, "Success make an order")
            return redirect("/")

        except stripe.error.CardError as e:
            body = e.json_body
            err = body.get("error", {})
            messages.error(self.request, f"{err.get('message')}")
            return redirect("/")

        except stripe.error.RateLimitError as e:
            # Too many requests made to the API too quickly
            messages.error(self.request, "To many request error")
            return redirect("/")

        except stripe.error.InvalidRequestError as e:
            # Invalid parameters were supplied to Stripe's API
            messages.error(self.request, "Invalid Parameter")
            return redirect("/")

        except stripe.error.AuthenticationError as e:
            # Authentication with Stripe's API failed
            # (maybe you changed API keys recently)
            messages.error(self.request, "Authentication with stripe failed")
            return redirect("/")

        except stripe.error.APIConnectionError as e:
            # Network communication with Stripe failed
            messages.error(self.request, "Network Error")
            return redirect("/")

        except stripe.error.StripeError as e:
            # Display a very generic error to the user, and maybe send
            # yourself an email
            messages.error(self.request, "Something went wrong")
            return redirect("/")

        except Exception as e:
            # Something else happened, completely unrelated to Stripe
            messages.error(self.request, "Not identified error")
            return redirect("/")


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(
        item=item, user=request.user, ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added quantity Item")
            return redirect("core:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "Item added to your cart")
            return redirect("core:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "Item added to your cart")
        return redirect("core:order-summary")


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, ordered=False
            )[0]
            order_item.delete()
            messages.info(
                request,
                'Item "' + order_item.item.item_name + '" remove from your cart',
            )
            return redirect("core:order-summary")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("core:product", pk=pk)
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("core:product", pk=pk)


@login_required
def reduce_quantity_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()
            messages.info(request, "Item quantity was updated")
            return redirect("core:order-summary")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("core:order-summary")
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("core:order-summary")

templates/core/home.html
{% extends '_base.html' %}
{% block content %}
    <!--Carousel Wrapper-->
    <div id="carousel-example-1z"
         class="carousel slide carousel-fade pt-4"
         data-ride="carousel">
        <!--Indicators-->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
            <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->
        <!--Slides-->
        <div class="carousel-inner" role="listbox">
            <!--First slide-->
            <div class="carousel-item active">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
                            background-repeat: no-repeat;
                            background-size: cover">
                </div>
            </div>
            <!--/First slide-->
            <!--Second slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg');
                            background-repeat: no-repeat;
                            background-size: cover">
                </div>
            </div>
            <!--/Second slide-->
            <!--Third slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg');
                            background-repeat: no-repeat;
                            background-size: cover">
                </div>
            </div>
            <!--/Third slide-->
        </div>
        <!--/.Slides-->
        <!--Controls-->
        <a class="carousel-control-prev"
           href="#carousel-example-1z"
           role="button"
           data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next"
           href="#carousel-example-1z"
           role="button"
           data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->
    </div>
    <main>
        <div class="container">
            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5 ps-3 pe-4">
                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>
                <!-- Collapse button -->
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#basicExampleNav"
                        aria-controls="basicExampleNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">
                    <!-- Links -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Outwears</a>
                        </li>
                    </ul>
                    <!-- Links -->
                    <form class="form-inline">
                        <div class="md-form my-0">
                            <input class="form-control me-sm-2"
                                   type="text"
                                   placeholder="Search"
                                   aria-label="Search"/>
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->
            </nav>
            <!--/.Navbar-->
            <!--Section: Products v.3-->
            <section class="text-center mb-4">
                <!--Grid row-->
                <div class="row wow fadeIn">
                    {% for item in object_list %}
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4">
                            <!--Card-->
                            <div class="card">
                                <!--Card image-->
                                <div class="view overlay">
                                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                         class="card-img-top"
                                         alt="">
                                    <a href="{{ item.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card image-->
                                <!--Card content-->
                                <div class="card-body text-center">
                                    <!--Category & Title-->
                                    <a href="" class="grey-text">
                                        <h5>{{ item.get_category_display }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.item_name }}
                                                <span class="badge badge-pill {% if item.get_label_display == 'New' %} danger-color {% else %} primary-color {% endif %}">{{ item.get_label_display }}</span>
                                            </a>
                                        </strong>
                                    </h5>
                                    <h4 class="font-weight-bold blue-text">
                                        <strong>$
                                            {% if item.discount_price %}
                                                {{ item.discount_price }}
                                            {% else %}
                                                {{ item.price }}
                                            {% endif %}
                                        </strong>
                                    </h4>
                                </div>
                                <!--Card content-->
                            </div>
                            <!--Card-->
                        </div>
                        <!--Grid column-->
                    {% endfor %}
                </div>
                <!--Grid row-->
            </section>
            <!--Section: Products v.3-->
            <!--Pagination-->
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">
                    <!--Arrow left-->
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="#">1
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">4</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">5</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <!--Pagination-->
        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/core/order_summary.html
{% extends '_base.html' %}
{% block content %}
    <main>
        <div class= "container">
            <div class="table-responsive text-nowrap">
                <h3>
                    <strong>Your Cart</strong>
                </h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Item Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order_item in object.items.all %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ order_item.item.item_name }}</td>
                                <td>
                                    {% if order_item.item.discount_price %}
                                        <del>${{ order_item.item.price }}</del>
                                        ${{ order_item.item.discount_price }}
                                    {% else %}
                                        ${{ order_item.item.price }}
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus me-2"></i></a>
                                    {{ order_item.quantity }}
                                    <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ms-2"></i></a>
                                </td>
                                <td>
                                    {% if order_item.item.discount_price %}
                                        ${{ order_item.get_discount_item_price }}
                                        <span class="badge badge-success">Saved ${{ order_item.get_amount_saved }}</span>
                                    {% else %}
                                        ${{ order_item.get_total_item_price }}
                                    {% endif %}
                                    <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                                        <i class="fas fa-trash float-right text-danger"></i>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5">Your Cart Empity</td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                    <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
                                </td>
                            </tr>
                        {% endfor %}
                        {% if object.get_total_price %}
                            <tr>
                                <td colspan="4">
                                    <b>Total Order Price</b>
                                </td>
                                <td>${{ object.get_total_price }}</td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                    <a href="{% url 'core:checkout' %}"
                                       class="btn btn-warning float-right ms-2">Checkout</a>
                                    <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
                                </td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{% endblock content %}

templates/core/product.html
{% extends '_base.html' %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <!--Content-->
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple me-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue me-1">{{ object.get_label_display }}</span>
              </a>
            </div>
            <p class="lead">
              {% if object.discount_price %}
                <span class="me-1">
                  <del>${{ object.price }}</del>
                </span>
                <span>${{ object.discount_price }}</span>
              {% else %}
                <span>${{ object.price }}</span>
              {% endif %}
            </p>
            <p class="lead font-weight-bold">{{ object.item_name }}</p>
            <p>{{ object.description }}</p>
            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ms-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}"
               class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ms-1"></i>
            </a>
            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}"
               class="btn btn-danger btn-md my-0 p">Remove From cart
              <i class="fas fa-trash ms-1"></i>
            </a>
          </div>
          <!--Content-->
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <hr>
      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.
          </p>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}