apps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    ProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("product/<pk>/", ProductView.as_view(), name="product"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payment/<payment_option>/", PaymentView.as_view(), name="payment"),
    path("add-to-cart/<pk>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<pk>/", remove_from_cart, name="remove-from-cart"),
    path(
        "reduce-quantity-item/<pk>/", reduce_quantity_item, name="reduce-quantity-item"
    ),
]

templates/0.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block css %}
{% endblock css %}
{% block content %}
    <h1>Home</h1>
{% endblock content %}
{% block js %}
{% endblock js %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="keywords" content="foo,bar" />
        <meta name="description" content="foo" />
        <title>
            {% block head_title %}
                Document
            {% endblock head_title %}
        </title>
        {% include "_styles.html" %}
        {% block extra_head %}
        {% endblock extra_head %}
    </head>
    <body>
        {% block body %}
            {% block navbar %}
                {% include "_navbar.html" %}
            {% endblock navbar %}
            <main>
                <div class="container">
                    {% block content %}
                    {% endblock content %}
                </div>
            </main>
        {% endblock body %}
        {% include "_scripts.html" %}
        {% include "_message.html" %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

templates/_message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>alertify.success('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>alertify.message('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>alertify.warning('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>alertify.error('{{ message }}')</script>
        {% else %}
            <script type=text/javascript>alertify.message('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

templates/_navbar.html
{% load static %}
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarToggler"
                aria-controls="navbarToggler"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% url 'accounts:home' as url %}
        <a class="navbar-brand me-lg-auto ms-md-auto"
           href="{% if request.path == url %}#{% else %}{{ url }}{% endif %}">
            <img src="{% static 'img/bootstrap-logo.svg' %}"
                 alt="Bootstrap"
                 width="40"
                 height="32"
                 class="d-inline-block align-text-top"/>
        </a>
        <div class="collapse navbar-collapse justify-content-around"
             id="navbarToggler">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% comment %} {% url 'users:home' as url %}
                    <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{url}}">Home</a>
                    {% endcomment %}
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                            {% if request.user|cart_item_count != 0 %}
                                <span class="badge red z-depth-1 me-1">{{ request.user|cart_item_count }}</span>
                            {% endif %}
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block">Cart</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hi {{ request.user | title }}</a>
                    </li>
                    <li class="nav-item">
                        {% url 'account_logout' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}"
                           href="{{ url }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        {% url 'account_login' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}"
                           href="{{ url }}">Login</a>
                    </li>
                    <li class="nav-item">
                        {% url 'account_signup' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}"
                           href="{{ url }}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/_scripts.html
{% load static %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'js/alertify.min.js' %}"></script>

templates/_styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/alertify.css' %}"/>
<link rel="stylesheet" href="{% static 'css/alertify.bootstrap.css' %}"/>